friendship v-1
atenaiis/ror-social-scaffold pull request #2
Opened 2021-04-12 17:39 UTC by atenaiis

Team

The aim is to create a model with associations and all requested features for friendships.

cheers!!

2021-04-12 18:44 UTC, rukundoeric requested changes
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The code looks clean and professional. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve
  - [ ] [MANDATORY] There is a test case that is failing. checkout this error: 
     ```
     NameError:
       undefined local variable or method `friendships_path' for #<RSpec::ExampleGroups::Friendships::GETFriendships:0x00007f8fa5f0c260>
     ```

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

2021-04-12 19:17 UTC, atenaiis commented
thank you for your comments.

I added the test for friendship_spec.

cheers!!!

2021-04-12 23:14 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @atenaiis 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [x] There is a one test case is pending at `spec/models/friendship_spec.rb`. You can write it or remove it.
**OPTIONAL**
- [ ] Your linter checks (GitHub Actions) are not running. Kindly ensure that all checks are running successfully.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-04-12 23:14 UTC, umairarshadbutt commented on spec/models/friendship_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Please remove the `pending` statement.

2021-04-13 00:35 UTC, atenaiis commented
Thanks for your comments

I removed the file .

Cheers!! :) :+1:

2021-04-13 01:17 UTC, BrianSammit approved these changes
STATUS: APPROVED :green_circle: :clap: 
-------------
Hello @atenaiis you did an amazing job working on the required changes :muscle: :100: 
------------
Now you can merge this branch :100: :+1: 
HAPPY CODING!! :smile: 
![Well-Done-Applause](https://user-images.githubusercontent.com/64173189/114482356-130a2e00-9bcc-11eb-99a1-c9d2951f4935.gif)

2021-04-13 03:23 UTC, merged